version: "3"
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-practice_ecommerce
        volumes:
            - .:/var/www/html


    mysql:
        image: mysql:8
        container_name: db
        ports:
            - "3307:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: shopping
            MYSQL_USER: app
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php





